name: medicine_reminder
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  flutter_intl: ^0.0.1
  intl: ^0.20.1
  flutter_svg: ^2.0.16
  firebase_messaging: ^15.2.0
  firebase_storage: ^12.4.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
